### ISSUE TITLE
Enhance Dockerfile

### ISSUE THREAD

**Issue by Sam-Sundar** [dilshadkp/dockerization-of-nodejs-application#1]
#Why use Alpine as base image if we can use node:alpine which has node already installed

FROM node:alpine

EXPOSE 8080
#WORKDIR creates folder automatically we don't need `run mkdir`
WORKDIR /var/nodeapp

COPY application/ .

RUN npm install

CMD ["node" , "mynodeapp.js"]

**Comment by dilshadkp** [comment]
Hi,
Size of node:alpine image is 169 MB and size of my image is only 60.2 MB.

```
REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
myimage      v1        efafba9bffc7   About a minute ago   60.2MB
alpine       latest    c059bfaa849c   5 days ago           5.59MB
node         alpine    9e17f47b0a78   2 weeks ago          169MB
```
That is why I opt installing node in a bare alpine image rather than taking a node:alpine image.

**Comment by dilshadkp** [comment]
@Sam-Sundar-Apty 

Hi,
Thanks for the suggestion. Size of node:alpine image is 169 MB and size of my image is only 60.2 MB.

```
REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
myimage      v1        efafba9bffc7   About a minute ago   60.2MB
alpine       latest    c059bfaa849c   5 days ago           5.59MB
node         alpine    9e17f47b0a78   2 weeks ago          169MB
```
That is why I opt installing node in a bare alpine image rather than taking a node:alpine image.
